#!/usr/bin/env python
from __future__ import print_function

import sys, os, getopt
import os.path
import iview.config

try:
	import configparser as ConfigParser  # Python 3
except ImportError:
	import ConfigParser  # Python 2

def usage():
	print("""usage:
	-i, --index		prints the iView index (number is the series ID)
	-s, --series <id>	get the list of episodes for the series
	-p, --programme		prints the entire iView programme at once
				(warning: very slow!)
	-d, --download <url>	download an episode
				(pass the url you got from -s or -p)
	-t, --subtitles <url>	download subtitles in SRT format for an episode
				(pass the same url as for --download)
	-o, --output		specify a file to output to (use - for stdout)
	    --batch <file>	specify a batch operation file (for cronjob etc)
	    --bindex            like --index but output is in batchfile format
	-a, --print-auth	print debug iView auth information
	-c, --cache <dir>	use cache directory for debugging
	-x, --proxy <host:port>	used specified SOCKS proxy
	-h, --help		this page""")

def config():
	try:
		iview.comm.get_config()
	except HTTPError as error:
		print('Error: could not retrieve an important configuration file from iView.')
		print('Please make sure you are connected to the Internet.\n')
		print('If iView works fine in your web browser, the iView API has possibly changed.' \
		      'Try to find an updated version of this program or contact the author.')
		print('\nDebug: could not load URL', error.url)
		sys.exit(1)

def programme():
	"""	Downloads the iView index, and then prints each item in all series.
		This is a slow function. Using index() and subsequently cherrypicking
		a series to pass to series() is much faster.
	"""
	config()
	index = iview.comm.get_keyword('index')

	for series in index:
		print(series['title'] + ':')
		print_series_items(series['items'], indent='\t')

def index():
	"""	Downloads the iView index, and prints the corresponding series and IDs.
	"""
	config()
	index = iview.comm.get_index()

	for series in index:
		print(series['id'] + '\t' + series['title'])

def batch_index():
	"""	Downloads the iView index, and prints the corresponding series and IDs in a format
		that works in the iview batch file
	"""
	config()
	index = iview.comm.get_index()

	for series in index:
		print(series['id'] + ': ' + series['title'])

def series(series_id):
	config()
	print_series_items(iview.comm.get_series_items(series_id))

def print_series_items(items, indent=''):
	for item in items:
		if item['livestream']:
			url = item['livestream']
		else:
			url = item['url']
		print(indent + item['title'] + '\t(' + url + ')')

def print_auth():
	config()
	auth = iview.comm.get_auth()
	print('iView auth data:')
	print('\tToken:', auth['token'])
	print('\tRTMP URL:', auth['rtmp_url'])
	print('\tPlaypath Prefix:', auth['playpath_prefix'])
	print('\tUnmetered:', str(auth['free']))

def download(url, output=None):
	config()
	iview.fetch.fetch_program(url, execvp=True, dest_file=output)

def batch(batch_file):
	config()

	# parse the batch file
	batch = ConfigParser.ConfigParser()
	batch.read(os.path.expanduser(batch_file))
	items = batch.items('batch')

	batch_destination = '.'
	series_ids = []
	last_only = False

	# separate options from the series ids
	for key, value in items:
		if key == 'destination':
			batch_destination = value
		elif key == 'last_only':
			if not(value == '0' or value.lower() == 'false' or value.lower() == "no"):
				last_only = True
		else:
			# Note: currently the value after the series_id in the batch file
			# is only used as a comment for the user.
			series_ids.append(key)

	# move to where the files should be downloaded
	os.chdir(batch_destination)

	# loop through the series ids
	for series_id in series_ids:

		# unset the last episode for the current series.
		last_episode = None

		# loop through the episodes
		episodes = iview.comm.get_series_items(series_id)
		for episode in episodes:
			if last_only:
				# This last_only feature is experimental, I am not sure which field to 
				# use to determine the most recent episode.
				if last_episode == None or episode['date'] > last_episode['date']:
					last_episode = episode
			else:
				batch_fetch_program(episode)

		# Last only means we only get one episode for the series
		if last_only:
			batch_fetch_program(last_episode)

def batch_fetch_program(episode):
	# Only print notification messages for episodes that have never been downloaded before.

	# urls sometimes include a path like 'news/' or 'kids/'
	(pathpart, filepart) = os.path.split(episode['url'])

	# urls also have '.mp4' extension but downloaded files end in '.flv'
	(base, ext) = os.path.splitext(filepart)

	if not os.path.isfile(base + '.flv'):
		print("getting " + episode['title'] + " - " + episode['url'])
	iview.fetch.fetch_program(episode['url'], execvp=False, dest_file=None, quiet=True)


def subtitles(name, output=None):
	# In this function, we print to sys.stderr because we have the possibility
	# of outputting subtitles to stdout, so we need to keep stdout clean.

	config()

	url = ''.join(name.split('.')[:-1])
	if output is not None:
		srt = output
	else:
		srt = ''.join(url.split('/')[-1]) + '.srt'

	if not srt == '-' and os.path.isfile(srt):
		print('Subtitles have already been downloaded to %s' % srt, file=sys.stderr)
		return False

	print('Downloading subtitles to %s...' % srt, end=' ', file=sys.stderr)

	try:
		subtitles = iview.comm.get_captions(url)
	except HTTPError as error:
		print('failed', file=sys.stderr)
		print('Got an error when downloading %s' % error.url, file=sys.stderr)
		return False
	except KeyboardInterrupt:
		return False

	if not srt == '-':
		f = open(srt, 'wb')
	else:
		f = sys.stdout

	f.write(subtitles.encode('utf-8'))
	f.flush()

	if not srt == '-':
		os.fsync(f.fileno())

	f.close()

	print('done', file=sys.stderr)

def parse_proxy_argument(proxy):
	"""	Try to parse 'proxy' as host:port pair.  Returns an error message
		if it cannot be understood.  Otherwise, it configures the settings
		in iview.config and returns None
	"""

	# this could be done much nicer with partition()
	# but it's not available in older versions of python
	parts = proxy.split(':')
	if len(parts) == 2:
		try:
			iview.config.socks_proxy_port = int(parts[1])
		except ValueError:
			return "Port '%s' is not numeric" % parts[1]
	elif len(parts) != 1:
		return "Too many ':' in '%s'" % proxy
	iview.config.socks_proxy_host = parts[0]

	return None

try:
	opts, args = getopt.getopt(sys.argv[1:], 'c:d:pis:t:x:o:ah', [
		'cache=',
		'subtitle=', 'subtitles=',
		'download=',
		'programme', 'program',
		'index',
		'series=',
		'proxy=',
		'output=',
		'batch=', 'bindex',
		'print-auth',
		'help',
	])
	if not len(opts) > 0:
		raise getopt.GetoptError('Not enough arguments')
except getopt.GetoptError as err:
	usage()
	sys.exit(2)

download_arg = None
subtitle_arg = None
output_arg = None
batch_arg = None

try:
	for o, a in opts:
		if o in ('-x', '--proxy'):
			err = parse_proxy_argument(a)
			if err is not None:
				print("Invalid proxy specification: %s\n" % err)
				usage()
				sys.exit(4)
		elif o in ('-d', '--download'):
			download_arg = a
		elif o in ('-t', '--subtitle', '--subtitles'):
			subtitle_arg = a
		elif o in ('-o', '--output'):
			output_arg = a
		elif o in ('--batch'):
			batch_arg = a
		elif o in ('-h', '--help'):
			usage()
			sys.exit(2)

	# iview.comm (and therefore iview.fetch) can only be imported after
	# configuring the proxy as we need to override the socket before
	# importing urllib
	import iview.fetch
	import iview.comm
	from iview.comm import HTTPError

	for o, a in opts:
		if o in ('-c', '--cache'):
			iview.comm.cache = a
		elif o in ('-p', '--programme', '--program'):
			programme()
		elif o in ('-i', '--index'):
			index()
		elif o in ('--bindex'):
			batch_index()
		elif o in ('-s', '--series'):
			series(a)
		elif o in ('-a', '--print-auth'):
			print_auth()

except KeyboardInterrupt: # don't traceback on a Ctrl+C
	pass

if download_arg is not None:
	download(download_arg, output_arg)
elif subtitle_arg is not None:
	subtitles(subtitle_arg, output_arg)
elif batch_arg is not None:
	batch(batch_arg)
